[tool.poetry]
name = "alabuga"
version = "0.1.0"
description = ""
authors = ["Alexandr Mamedov <anifan01@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
icecream = "^2.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
